apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickcicd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quickcicd
  template:
    metadata:
      labels:
        app: quickcicd
    spec:
      containers:
        - name: quick-cicd
          image: serbayacarsys/quick-cicd:latest
          ports:
            - containerPort: 8000
