apiVersion: v1
kind: Service
metadata:
  name: quick-ci-cd-service
spec:
  type: ClusterIP
  selector:
    app: quickcicd
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32080
